/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package puzzle;

import java.awt.Image;
import static java.awt.Image.SCALE_SMOOTH;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static puzzle.NewJFrame.state;
import static puzzle.login.usernameLogin;


/**
 *
 * @author DELL
 */
public class Congrats extends javax.swing.JFrame {

    /**
     * Creates new form Congrats
     */
    public Congrats() {
        initComponents();
        NewJFrame n = new NewJFrame();
        username.setText(usernameLogin.getText());
        labelphoto("C:\\Users\\DELL\\OneDrive\\Documents\\NetBeansProjects\\Datamodel\\pink.png" , pink);
        labelphoto("C:\\Users\\DELL\\OneDrive\\Documents\\NetBeansProjects\\Datamodel\\beij.png" , purple);
        labelphoto("C:\\Users\\DELL\\OneDrive\\Documents\\NetBeansProjects\\Datamodel\\purple.png" , beij);
        labelphoto("C:\\Users\\DELL\\OneDrive\\Documents\\NetBeansProjects\\Datamodel\\pink.png" , blue);
        labelphoto("C:\\Users\\DELL\\OneDrive\\Documents\\NetBeansProjects\\Datamodel\\yellow.png" , green);
        labelphoto("C:\\Users\\DELL\\OneDrive\\Documents\\NetBeansProjects\\Datamodel\\green.png" , yellow);
      
    }
     public void labelphoto(String path, JLabel c){
        ImageIcon icon = new ImageIcon(path);
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(c.getWidth(), c.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        c.setIcon(scaledIcon);

    
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pink = new javax.swing.JLabel();
        purple = new javax.swing.JLabel();
        yellow = new javax.swing.JLabel();
        beij = new javax.swing.JLabel();
        blue = new javax.swing.JLabel();
        green = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        moves = new javax.swing.JLabel();
        score = new javax.swing.JLabel();
        newgame = new javax.swing.JButton();
        report = new javax.swing.JButton();
        username = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Result");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(157, 210, 216));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 27)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(66, 60, 109));
        jLabel1.setText("Congratulations,");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 190, -1));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 27)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(251, 105, 98));
        jLabel2.setText("Time");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 27)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(251, 105, 98));
        jLabel3.setText("Moves");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 27)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(251, 105, 98));
        jLabel4.setText("Score");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, -1, -1));
        jPanel1.add(pink, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 70, 60));
        jPanel1.add(purple, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 32, 70, 49));
        jPanel1.add(yellow, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 53, 78, 63));
        jPanel1.add(beij, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 150, 80, 60));
        jPanel1.add(blue, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 82, 63));
        jPanel1.add(green, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 80, 54));

        time.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 27)); // NOI18N
        time.setText("jLabel6");
        jPanel1.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, -1, -1));

        moves.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 27)); // NOI18N
        moves.setText("jLabel7");
        jPanel1.add(moves, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, -1, -1));

        score.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 27)); // NOI18N
        score.setText("jLabel8");
        jPanel1.add(score, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, -1, -1));

        newgame.setBackground(new java.awt.Color(66, 60, 109));
        newgame.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        newgame.setForeground(new java.awt.Color(252, 252, 153));
        newgame.setText("New Game");
        newgame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newgameActionPerformed(evt);
            }
        });
        jPanel1.add(newgame, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 140, 40));

        report.setBackground(new java.awt.Color(66, 60, 109));
        report.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        report.setForeground(new java.awt.Color(252, 252, 153));
        report.setText("Report");
        report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportActionPerformed(evt);
            }
        });
        jPanel1.add(report, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 450, 140, 40));

        username.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 27)); // NOI18N
        username.setText("jLabel5");
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 140, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 530));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void newgameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newgameActionPerformed
        // TODO add your handling code here:
        //////////////////////////////////
        table t = new table();
        Report r = new Report();
        NewJFrame n = new NewJFrame();
        selectimage select = new selectimage();
        n.state = true;
       //state=false; 
       //restart timer
       n.hours=0;
       n.seconds=0;
       n.minutes=0;
       n.milliseconds=0;
       
       n.milisecond.setText("00"); 
       n.second.setText(" 00 "); 
       n.minute.setText(" 00"); 
      // n.hour.setText("00 ");
      
        select.setVisible(true);
        select.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        ///////////////////////////////
    }//GEN-LAST:event_newgameActionPerformed

    private void reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportActionPerformed
        // TODO add your handling code here:
        table t = new table();
        Report r = new Report();
        r.display_file("C:\\Users\\DELL\\OneDrive\\Documents\\NetBeansProjects\\puzzle\\result.txt", t);
        t.setVisible(true);
        t.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_reportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Congrats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Congrats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Congrats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Congrats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Congrats().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel beij;
    private javax.swing.JLabel blue;
    private javax.swing.JLabel green;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel moves;
    private javax.swing.JButton newgame;
    private javax.swing.JLabel pink;
    private javax.swing.JLabel purple;
    private javax.swing.JButton report;
    public javax.swing.JLabel score;
    public javax.swing.JLabel time;
    public javax.swing.JLabel username;
    private javax.swing.JLabel yellow;
    // End of variables declaration//GEN-END:variables
}
