/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package puzzle;

import java.awt.Image;
import static java.lang.Thread.sleep;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static puzzle.NewJFrame.seconds;
/*import students.pu.picpuzzle2;*/

/**
 *
 * @author yara
 */
public class selectimage extends javax.swing.JFrame {

    /**
     * Creates new form selectimage
     */
    public int x;
    private String[][] address=new String[3][3];
    public selectimage() {
        initComponents();
        this.setLocationRelativeTo(null);
        scaleImage();
        scaleImage2();
        scaleImage3();
    }
    /*
    "D:\EDUCATION\Level Two\L.2-S.1 2020\Programing Language 2\Project\puzzle\puzzelpic\puzzel11.jpg"
    */
    public void  scaleImage(){
        ImageIcon icon=new ImageIcon(" C:\\puzzel11.jpg " );
        Image img=icon.getImage();
        Image imgscale=img.getScaledInstance(jLabelpic1.getWidth(),jLabelpic1.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon scaledIcon=new ImageIcon(imgscale);
        jLabelpic1.setIcon(scaledIcon);
    }
    public void  scaleImage2(){
        ImageIcon icon=new ImageIcon("C:\\Users\\DELL\\OneDrive\\Documents\\NetBeansProjects\\puzzle\\puzzelpic\\puzzel22.jpg");
        Image img=icon.getImage();
        Image imgscale=img.getScaledInstance(jLabelpic2.getWidth(),jLabelpic2.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon scaledIcon=new ImageIcon(imgscale);
        jLabelpic2.setIcon(scaledIcon);
    }
    public void  scaleImage3(){
        ImageIcon icon=new ImageIcon("C:\\Users\\DELL\\OneDrive\\Documents\\NetBeansProjects\\puzzle\\puzzelpic\\puzzel33.jpg");
        Image img=icon.getImage();
        Image imgscale=img.getScaledInstance(jLabelpic3.getWidth(),jLabelpic3.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon scaledIcon=new ImageIcon(imgscale);
        jLabelpic3.setIcon(scaledIcon);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabelpic1 = new javax.swing.JLabel();
        jLabelpic2 = new javax.swing.JLabel();
        jLabelpic3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(157, 210, 216));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 60)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(66, 60, 109));
        jLabel2.setText("Select One Picture");

        jLabelpic1.setBackground(new java.awt.Color(51, 0, 51));
        jLabelpic1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.black, null, null));
        jLabelpic1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelpic1MouseClicked(evt);
            }
        });

        jLabelpic2.setBackground(new java.awt.Color(51, 0, 51));
        jLabelpic2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.black, null, null));
        jLabelpic2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelpic2MouseClicked(evt);
            }
        });

        jLabelpic3.setBackground(new java.awt.Color(51, 0, 51));
        jLabelpic3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.black, null, null));
        jLabelpic3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelpic3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabelpic1, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelpic2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelpic3, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelpic3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabelpic2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabelpic1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(111, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelpic1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelpic1MouseClicked
        // TODO add your handling code here:
        x=1;
       /* picpuzzle2.setPicID(x);
        picpuzzle2 pul=new picpuzzle2();
        pul.setVisible(true);
        pul.pack();
        pul.setLocationRelativeTo(null);
        pul.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
         pu pic=new pu();*/
         
        NewJFrame.setPicID(x);
        // NewJFrame frame=new NewJFrame();
        NewJFrame n=new NewJFrame();
        n.setVisible(true);
        n.pack();
        n.setLocationRelativeTo(null);
        n.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        
         Thread T= new Thread(){
           
         public void run(){
        // P.calculateTime();
         while(seconds<60){
           
        if(n.state==true){
            try{
           sleep(1);
            if(n.milliseconds>1000){
            n.milliseconds=0;
            seconds++;     }
           
           if(seconds>60){
            seconds=0;
            n.minutes++;     }
               
             if(n.minutes>60){
            seconds=0;
            n.minutes=0;
            n.hours++;     }
            n.milliseconds++; }
            
  catch (Exception e) {   
                
                       
            }
       n.milisecond.setText(" : "+n.milliseconds); 
       n.second.setText(" : "+seconds); 
       n.minute.setText(" : "+n.minutes); 
      // hour.setText(" : "+hours);
       
        }
         }
      
       JOptionPane.showMessageDialog(rootPane, "Time's Up!");
       Hardluck h = new Hardluck();
       h.setVisible(true);
               
      
         }; 
        };
           
           
            T.start();   
         
        
        
       
    }//GEN-LAST:event_jLabelpic1MouseClicked

    private void jLabelpic2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelpic2MouseClicked
        // TODO add your handling code here
        
        x=2;
        NewJFrame.setPicID(x);
        // NewJFrame frame=new NewJFrame();
        NewJFrame n=new NewJFrame();
        n.setVisible(true);
        n.pack();
        n.setLocationRelativeTo(null);
        n.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        
           Thread T= new Thread(){
           
         public void run(){
        // P.calculateTime();
         while(seconds<60){
           
        if(n.state==true){
            try{
           sleep(1);
            if(n.milliseconds>1000){
            n.milliseconds=0;
            seconds++;     }
           
           if(seconds>60){
            seconds=0;
            n.minutes++;     }
               
             if(n.minutes>60){
            seconds=0;
            n.minutes=0;
            n.hours++;     }
            n.milliseconds++; }
            
  catch (Exception e) {   
                
                       
            }
       n.milisecond.setText(" : "+n.milliseconds); 
       n.second.setText(" : "+seconds); 
       n.minute.setText(" : "+n.minutes); 
      // hour.setText(" : "+hours);
       
        }
         }
      
       JOptionPane.showMessageDialog(rootPane, "Time's Up!");
       Hardluck h = new Hardluck();
       h.setVisible(true);
               
      
         }; 
        };
           
           
            T.start();
        
    }//GEN-LAST:event_jLabelpic2MouseClicked

    private void jLabelpic3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelpic3MouseClicked
        // TODO add your handling code here:
          x=3;
          NewJFrame.setPicID(x);
        // NewJFrame frame=new NewJFrame();
        NewJFrame n=new NewJFrame();
        n.setVisible(true);
        n.pack();
        n.setLocationRelativeTo(null);
        n.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        
           Thread T= new Thread(){
           
         public void run(){
        // P.calculateTime();
         while(seconds<60){
           
        if(n.state==true){
            try{
           sleep(1);
            if(n.milliseconds>1000){
            n.milliseconds=0;
            seconds++;     }
           
           if(seconds>60){
            seconds=0;
            n.minutes++;     }
               
             if(n.minutes>60){
            seconds=0;
            n.minutes=0;
            n.hours++;     }
            n.milliseconds++; }
            
  catch (Exception e) {   
                
                       
            }
       n.milisecond.setText(" : "+n.milliseconds); 
       n.second.setText(" : "+seconds); 
       n.minute.setText(" : "+n.minutes); 
      // hour.setText(" : "+hours);
       
        }
         }
      
       JOptionPane.showMessageDialog(rootPane, "Time's Up!");
       Hardluck h = new Hardluck();
       h.setVisible(true);
               
      
         }; 
        };
           
           
            T.start();
         
    }//GEN-LAST:event_jLabelpic3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(selectimage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(selectimage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(selectimage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(selectimage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new selectimage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelpic1;
    private javax.swing.JLabel jLabelpic2;
    private javax.swing.JLabel jLabelpic3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
